"""empty message

Revision ID: 387b9fb2d9c2
Revises: da83096d52c6
Create Date: 2021-04-14 13:06:07.248019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '387b9fb2d9c2'
down_revision = 'da83096d52c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pinjam',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('idbuku', sa.BigInteger(), nullable=False),
    sa.Column('idmember', sa.BigInteger(), nullable=False),
    sa.Column('tanggalpinjam', sa.DateTime(), nullable=True),
    sa.Column('tanggalkembali', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['idbuku'], ['buku.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['idmember'], ['member.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pinjam')
    # ### end Alembic commands ###
