"""empty message

Revision ID: 4090471e80ab
Revises: 
Create Date: 2021-04-12 22:47:03.724280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4090471e80ab'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buku',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('judulbuku', sa.String(length=100), nullable=False),
    sa.Column('pengarang', sa.String(length=100), nullable=False),
    sa.Column('penerbit', sa.String(length=100), nullable=False),
    sa.Column('tahunterbit', sa.String(length=100), nullable=False),
    sa.Column('kategori', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('buku')
    # ### end Alembic commands ###
