"""empty message

Revision ID: 80e4a165261b
Revises: 4090471e80ab
Create Date: 2021-04-12 22:55:30.789088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80e4a165261b'
down_revision = '4090471e80ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('member',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tipe', sa.String(length=100), nullable=False),
    sa.Column('nama', sa.String(length=100), nullable=False),
    sa.Column('tempatlahir', sa.String(length=100), nullable=False),
    sa.Column('tanggallahir', sa.DateTime(), nullable=False),
    sa.Column('jeniskelamin', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('alamat', sa.String(length=100), nullable=False),
    sa.Column('pekerjaan', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('member')
    # ### end Alembic commands ###
